### ISSUE TITLE
Goodra's Broken

### ISSUE THREAD

**Issue by DeVoutNumelran** [PerfectRaito/StarboundSimpleVoreMod#27]
I wanted to post this since I was quite surprised that there wasnt anyone at all posting these things.

First of All. I noticed that often, the Getting eaten doesnt always work. Often times the NPC gets the full belly sprite, but Your player doesnt get effected, you can even move freely. 

So far I managed to spawn the NPC Goodra, and she is the most broken. When she eats you, she instantly teleports away and her Colony Deed turns into a short Healing Icon before she respawns. This also Locks you in place, forcing you to go to your ship and back to fix it.

I hope this helps. I will post more when I see them.

**Comment by DeVoutNumelran** [comment]
Same issue as goodra Happens with the Green Dragon NPC.

**Comment by Sheights** [comment]
This was fixed as of 6.3.1. The issue was all of the functions that called for sounds was incorrectly referencing the predator entity causing a null value. When the script crashes the NPC dies. Goodra and the Green Dragon both share the same main script. Go to the releases section and download the latest version. Should be fixed.

Thank you for your input!
